---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: vmsingle
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: grafana-observability
  datasource:
    type: prometheus
    name: prometheus
    access: proxy
    isDefault: true
    url: http://vmsingle-victoria-metrics.observability.svc.cluster.local:8428
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: vmalertmanager
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: grafana-observability
  datasource:
    type: alertmanager
    name: alertmanager
    access: proxy
    jsonData:
      implementation: prometheus
    url: http://vmalertmanager-victoria-metrics.observability.svc.cluster.local:9093
# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/grafana.integreatly.org/grafanadatasource_v1beta1.json
# apiVersion: grafana.integreatly.org/v1beta1
# kind: GrafanaDatasource
# metadata:
#   name: loki
# spec:
#   instanceSelector:
#     matchLabels:
#       app.kubernetes.io/instance: grafana-observability
#   datasource:
#     type: loki
#     name: loki
#     access: proxy
#     url: http://loki-headless.observability.svc.cluster.local:3100
