# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: doppler-secret
stringData:
  token: ENC[AES256_GCM,data:ZmjhYJ1F+uGOsxRRJpPX77qFxLTjWJZMAlSZZI29lWNtBCYEB58ugfIqNl83oFrrpkNO7ac=,iv:GEeerQjhpNnpP2caeSX916yeIDv800Y+7yvWxrJa32M=,tag:zG+HKlSLIxVRFV4b0iRYZQ==,type:str]
sops:
  age:
    - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSDF5djlrQ1dHRmc5Qkd1
        RldqaG51ZXF2azh0emVMODVsdm1Zay96eFJNCnNHK0xwcWlMTXppUldzbyt2akpv
        OEh3TnpDUW5RMVo5ZlVweHNZZlR0WEUKLS0tIE9LbnNmS2VSWFgwaGd5aVFCcHBH
        Y0xnYWtGMGp1MmJFdUVUMXFZUWRGWXcKy0v9UDtY/z5VGEohNdQ1cDfAVEPJid9t
        NHnysb+R4KPJMK7QWQkAKc4sFYOboYsnAf+gwwLYJYPYeMueBKaasw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T14:53:54Z"
  mac: ENC[AES256_GCM,data:ZqGcn84sTWZu3SIV9tKkWLiyBVBbIwHNy+7v1CSAdJVBf6a9YaPiKKXnFVWj+rROYqoOid0whJTEekvw5TlD4VYgii1uJ7E32am/Tsk97mWB9ozsfzrLLzTOJtXfaFldK2D4/YEJ0fGwiCrJv8t5QfMtMxpOmG+XQgf8v84izag=,iv:+Sv8Pko4c5g50tvT+uR0O+5JWVQSi6iRGtCamBakoe4=,tag:sasa5V7GLpqaJgoZ98dbaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
