---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
  path: /kubernetes/apps/external-secrets/external-secrets/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: external-secrets
  interval: 30m
  timeout: 5m
  wait: true
  prune: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
  path: /kubernetes/apps/external-secrets/external-secrets/stores
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: external-secrets
  interval: 30m
  prune: true
