---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  path: /kubernetes/apps/observability/prometheus-operator-crds/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: observability
  interval: 30m
  retryInterval: 2m
  timeout: 3m
  wait: true
  prune: false
