---
ci:
  autoupdate_schedule: quarterly
  skip:
    - renovate-config-validator  # node@lts exceeds tier max size 250MiB: 620MiB

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/sirosen/texthooks
    rev: 0.7.1
    hooks:
      - id: fix-smartquotes
      - id: fix-spaces
      - id: fix-unicode-dashes

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint

  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.5.4
    hooks:
      - id: renovate-config-validator
        files: "renovate(rc|/.+)?\\.json5?$"

  - repo: https://github.com/ansible/ansible-lint
    rev: v26.1.1
    hooks:
      - id: ansible-lint
        args:
          - ansible/  # without, ansible-lint always checks all files

  - repo: local
    hooks:
      - id: kubeconform
        name: kubeconform
        entry: ghcr.io/yannh/kubeconform:v0.7.0
        language: docker_image
        files: ^kubernetes/
        args:
          - -summary
          - -schema-location
          - default
          - -schema-location
          - https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
          - -schema-location
          - https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/{{.ResourceKind}}.json
          - -ignore-filename-pattern
          - resources/
          - -ignore-filename-pattern
          - helmfile\.ya?ml
          - -ignore-filename-pattern
          - helm-values\.ya?ml
          - -ignore-filename-pattern
          - transformer-config\.ya?ml
