---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret ring-mqtt-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.json: |-
          {
            "mqtt_url": "mqtt://{{ .mqtt_user }}:{{ .mqtt_password }}@mosquitto:1883",
            "enable_modes": true
          }
  dataFrom:
    - extract:
        key: RING_MQTT
