---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
    - name: longhorn
    - name: traefik-crds
  path: /kubernetes/apps/default/vaultwarden/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  interval: 30m
  timeout: 5m
  wait: true
  prune: true
