---
devices:

  - name: conbee2
    groups:
      - paths:
          - path: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2487785-if00

  - name: tun
    groups:
      - count: 10
        paths:
          - path: /dev/net/tun

  - name: vpu
    groups:
      - paths:
          - path: /dev/mpp_service
          - path: /dev/rga
          - path: /dev/mali0
          - path: /dev/dri
          - path: /dev/dma_heap

  - name: npu
    groups:
      - paths:
          - path: /dev/dri
