---
devices:

  - name: conbee2
    groups:
      - paths:
          - path: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2487785-if00

  - name: tun
    groups:
      - count: 10
        paths:
          - path: /dev/net/tun

  # Rockchip & Jellyfin
  # See: https://jellyfin.org/docs/general/post-install/transcoding/hardware-acceleration/rockchip/
  - name: dma-heap
    groups:
      - paths:
          - path: /dev/dma_heap
  - name: dri
    groups:
      - paths:
          - path: /dev/dri
  - name: mali0
    groups:
      - paths:
          - path: /dev/mali0
  - name: mpp-service
    groups:
      - paths:
          - path: /dev/mpp_service
  - name: rga
    groups:
      - paths:
          - path: /dev/rga
