---
devices:

  - name: conbee2
    groups:
      - paths:
          - path: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2487785-if00

  - name: tun
    groups:
      - count: 10
        paths:
          - path: /dev/net/tun

  - name: vpu
    groups:
      - paths:
          - path: /dev/mpp_service
          - path: /dev/rga
          - path: /dev/mali0
          - path: /dev/dri/renderD128
          - path: /dev/dma_heap/system
          - path: /dev/dma_heap/system-uncached

  - name: npu
    groups:
      - paths:
          - path: /dev/dri/renderD129
          - path: /dev/dma_heap/system
          - path: /dev/dma_heap/system-uncached
          - path: /dev/rknpu
        mounts:
          - hostPath: /sys/firmware/devicetree/base
            containerPath: /proc/device-tree
            readOnly: true
          - hostPath: /sys/class/drm
            containerPath: /sys/class/drm
            readOnly: true
          - hostPath: /sys/devices
            containerPath: /sys/devices
            readOnly: true
          - hostPath: /usr/lib/aarch64-linux-gnu/libmali.so.1.9.0
            containerPath: /usr/lib/libmali.so
            readOnly: true
          - hostPath: /usr/lib/librknnrt.so
            containerPath: /usr/lib/librknnrt.so
            readOnly: true
