---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  namespace: network
spec:
  headers:
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
  namespace: network
spec:
  compress:
    minResponseBodyBytes: 1024
    excludedContentTypes:
      - application/zip
      - application/octet-stream
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-authelia
  namespace: network
spec:
  forwardAuth:
    address: http://authelia.auth.svc.cluster.local:9091/api/authz/forward-auth
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Name
      - Remote-Email
      - Remote-Groups
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain
  namespace: network
spec:
  chain:
    middlewares:
      - name: secure-headers
      - name: compress
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-chain
  namespace: network
spec:
  chain:
    middlewares:
      - name: secure-headers
      - name: forwardauth-authelia
      - name: compress
# NOTE: we need to create this in each namespace for the Gateway API :(
# I've opened an idea that perhaps a ReferenceGrant can be used for this
# See: https://github.com/kubernetes-sigs/gateway-api/discussions/4340
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-chain
  namespace: default
spec:
  chain:
    middlewares:
      - name: network-secure-headers@kubernetescrd
      - name: network-forwardauth-authelia@kubernetescrd
      - name: network-compress@kubernetescrd
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-chain
  namespace: home-automation
spec:
  chain:
    middlewares:
      - name: network-secure-headers@kubernetescrd
      - name: network-forwardauth-authelia@kubernetescrd
      - name: network-compress@kubernetescrd
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-chain
  namespace: longhorn-system
spec:
  chain:
    middlewares:
      - name: network-secure-headers@kubernetescrd
      - name: network-forwardauth-authelia@kubernetescrd
      - name: network-compress@kubernetescrd
