---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
  path: /kubernetes/apps/flux-system/flux-operator/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-system
  interval: 30m
  timeout: 3m
  retryInterval: 2m
  wait: true
  prune: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-instance
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-operator
  path: /kubernetes/apps/flux-system/flux-operator/instance
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-system
  interval: 30m
  timeout: 3m
  retryInterval: 2m
  prune: true
