---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  driftDetection:
    mode: enabled
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            # fsGroup: &mediaGroup 65537
            # fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        initContainers:
          coredns:
            image:
              repository: coredns/coredns
              tag: 1.14.1@sha256:82b57287b29beb757c740dbbe68f2d4723da94715b563fffad5c13438b71b14a
            args: ["-conf", "/etc/coredns/Corefile"]
            restartPolicy: Always
          gluetun:
            dependsOn: coredns
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
            restartPolicy: Always
            lifecycle:
              postStart:
                exec:
                  # See: https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/kubernetes.md#adding-ipv6-rule--file-exists
                  command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true"]
            env:
              TZ: ${TIME_ZONE}
              LOG_LEVEL: info
              PUID: &gluetunUser 0  # needed for iptables
              PGID: &gluetunGroup 6001
              FIREWALL_INPUT_PORTS: &port 8080
              FIREWALL_OUTBOUND_SUBNETS: ${LAN_CIDR},${LAN_CIDRv6},${CLUSTER_CIDR},${CLUSTER_CIDRv6},${SERVICE_CIDR}
              BLOCK_MALICIOUS: "off"
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              VPN_SERVICE_PROVIDER: protonvpn
              SERVER_COUNTRIES: Netherlands
              PORT_FORWARD_ONLY: "on"
              VPN_PORT_FORWARDING: "on"
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              VPN_PORT_FORWARDING_UP_COMMAND: >-
                /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{"{{"}}PORTS{{"}}"}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
              UPDATER_PERIOD: 24h
              UPDATER_VPN_SERVICE_PROVIDERS: protonvpn
              WIREGUARD_ADDRESSES: 10.2.0.2/32
              WIREGUARD_MTU: 1420
            envFrom:
              - secretRef:
                  name: qbittorrent-gluetun-secret
            probes:
              liveness: &gluetunProbe
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /gluetun-entrypoint
                      - healthcheck
                  initialDelaySeconds: 15
                  periodSeconds: 60
                  failureThreshold: 10
              readiness: *gluetunProbe
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
                squat.ai/tun: "1"
            securityContext:
              runAsUser: *gluetunUser
              runAsGroup: *gluetunGroup
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false  # See: https://github.com/qdm12/gluetun/discussions/2797
              capabilities:
                drop:
                  - ALL
                add:
                  - NET_ADMIN
                  - NET_RAW
                  - SYS_MODULE  # Kernel space Wireguard
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.4@sha256:56ecd30a7f5e1357daf5eea2a6935134d329b7b268a3a9b9c67041b65fb87fc6
            env:
              TZ: ${TIME_ZONE}
              UMASK: "022"
              QBT_WEBUI_PORT: *port
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              runAsNonRoot: true
              runAsUser: 6000
              runAsGroup: 65537
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 250m
                memory: 256Mi
              limits:
                memory: 1Gi
          # exporter:
          #   image:
          #     repository: ghcr.io/esanchezm/prometheus-qbittorrent-exporter
          #     tag: v1.6.0@sha256:b987d19693a5b2fe7314b22009c6302e084ec801fcf96afaf14065b4cdafc842
          #   env:
          #     QBITTORRENT_HOST: localhost
          #     QBITTORRENT_PORT: *appport
          #     EXPORTER_PORT: &metricsport 17871
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: qbittorrent-config
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      downloads:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/media/Downloads
        advancedMounts:
          qbittorrent:
            app:
              - path: /media/Downloads
      gluetun:
        type: persistentVolumeClaim
        existingClaim: gluetun-data
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: /gluetun
      tmpfs:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: /tmp/gluetun
      coredns:
        type: configMap
        name: qbittorrent-coredns
        advancedMounts:
          qbittorrent:
            coredns:
              - path: /etc/coredns/Corefile
                subPath: Corefile
      # Kernel space Wireguard
      # See: https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/wireguard.md
      modules:
        type: hostPath
        hostPath: /lib/modules
        hostPathType: Directory
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: /lib/modules
                readOnly: true
    service:
      app:
        ports:
          http:
            port: *port
            protocol: HTTP
          # metrics:
          #   port: *metricsport
          #   protocol: HTTP
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: qBittorrent
          gethomepage.dev/icon: qbittorrent
          gethomepage.dev/description: Lightweight, open-source bittorrent client
          gethomepage.dev/group: Media
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
