---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  external:
    url: http://grafana.observability.svc.cluster.local
    adminUser:
      name: grafana-admin-secret
      key: admin-user
    adminPassword:
      name: grafana-admin-secret
      key: admin-password
