---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  path: /kubernetes/apps/traefik/traefik/crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: traefik
  prune: true
  interval: 15m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-issuers
    - name: metallb-pools
    - name: prometheus-operator-crds
    - name: traefik-crds
  path: /kubernetes/apps/traefik/traefik/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: traefik
  prune: true
  interval: 15m
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-middleware
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-crds
  path: /kubernetes/apps/traefik/traefik/middleware
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  interval: 15m
  timeout: 5m
