---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
    - name: traefik
  path: /kubernetes/apps/observability/victoria-metrics/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: observability
  interval: 30m
  retryInterval: 3m
  timeout: 5m
  wait: true
  prune: true
