---
collections:

  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: bc3f66be7b224de78833b6cfbdd92b4adb0219d4

  - name: kubernetes.core
    type: galaxy
    version: 6.3.0

  - name: community.general
    type: galaxy
    version: 7.5.2
