---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/kubernetes-csi/external-snapshotter
  ref:
    tag: v8.5.0
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-crds
  namespace: flux-system
spec:
  path: /client/config/crd
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  targetNamespace: kube-system
  interval: 30m
  timeout: 5m
  prune: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: external-snapshotter-crds
  path: /deploy/kubernetes/snapshot-controller
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  targetNamespace: kube-system
  interval: 30m
  timeout: 5m
  wait: true
  prune: true
