---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/mcsrobert/homelab
        - Asus RT-AX86S:
            - abbr: RT
              href: https://asus-wifi-router.fritz.box:8443
  custom.css: |
    .information-widget-longhorn-node {
        margin-left: 1rem; /* Equivalent to ml-4 */ !important
    }
  custom.js: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    gateway: true
  proxmox.yaml: ""
  settings.yaml: |
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system.svc.cluster.local
  services.yaml: |
    - Infrastructure:
        - MetalLB:
            description: Bare-metal load-balancing for Kubernetes
            icon: metallb
            app: metallb
            namespace: network
    - Observability:
        - Prometheus:
            description: Metrics and time-series database
            icon: prometheus
            app: prometheus
            namespace: observability
    - Network:
        - FRITZ!Box 5590:
            href: http://fritz.box
            description: Fiber modem and WiFi 6 router
            icon: avm-fritzbox
            widget:
              type: fritzbox
              url: http://192.168.178.1
        - Traefik:
            description: Modern reverse proxy for applications
            icon: traefik-proxy
            namespace: traefik
            app: traefik
        - Tailscale:
            href: https://login.tailscale.com/admin/machines
            description: Zero-config VPN with WireGuard.
            icon: tailscale
            app: tailscale
            namespace: network
            podSelector: ""
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "total"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
