---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      server:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 11100
            runAsGroup: &nfsGroup 65539
            fsGroup: *nfsGroup
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.5.6@sha256:aa163d2e1cc2b16a9515dd1fef901e6f5231befad7024f093d7be1f2da14341a
            env:
              !!merge <<: &sharedEnv
                TZ: ${TIME_ZONE}
                PUBLIC_IMMICH_SERVER_URL: https://immich.${CLUSTER_DOMAIN}
                IMMICH_SERVER_URL: http://immich-server:2283
                IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
                DB_URL:
                  secretKeyRef:
                    name: immich-cnpg-app
                    key: uri
              REDIS_HOSTNAME: immich-dragonfly
              REDIS_PASSWORD:
                secretKeyRef:
                  name: immich-dragonfly-secret
                  key: password
              UPLOAD_LOCATION: &uploadPath /usr/src/app/upload
              IMMICH_TELEMETRY_INCLUDE: all
            envFrom: &envFrom
              - secretRef:
                  name: immich-secret
            probes: &probes
              liveness: &probe
                enabled: true
              readiness: *probe
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
        # pod:
        #   securityContext:
        #     runAsUser: 11110
        #     runAsGroup: 11110
        #     fsGroup: 11110
        #   hostUsers: false
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.5.6-rknn@sha256:96a8fe4530b8a242e60e92d54c62607e5539dbfff7735779d46141d94c83af33
            env:
              !!merge <<: *sharedEnv
              IMMICH_LOG_LEVEL: info
              MACHINE_LEARNING_RKNN: "true"
              MACHINE_LEARNING_RKNN_THREADS: "3"
            envFrom: *envFrom
            probes: *probes
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
                squat.ai/npu: 1
            securityContext:
              # TODO: run as non root when kernel supports it
              privileged: true
              # I'm running Rockchip BSP 6.1 currently, which does not support
              # "procMount: Unmasked", which is needed for /proc/device-tree/compatible
              # Per the docs: "In practice this means you need at least Linux
              # 6.3, as tmpfs started supporting idmap mounts in that version.
              # This is usually needed as several Kubernetes features use tmpfs
              # (the service account token that is mounted by default uses a
              # tmpfs, Secrets use a tmpfs, etc.)
              # ---
              # supplementalGroups: [44, 105]  # video, render
              # appArmorProfile:
              #   type: Unconfined
              # seccompProfile:
              #   type: Unconfined
              # allowPrivilegeEscalation: false
              # readOnlyRootFilesystem: true
              # capabilities:
              #   add:
              #     - IPC_LOCK
    persistence:
      upload:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/immich
        advancedMounts:
          server:
            app:
              - path: *uploadPath
      # tmpfs:
      #   type: emptyDir
      #   advancedMounts:
      #     machine-learning:
      #       app:
      #         - path: /cache
      #           subPath: cache
      #         - path: /.cache
      #           subPath: internal-cache
      #         - path: /.config
      #           subPath: config
      #         - path: /tmp
      #           subPath: tmp
    service:
      server:
        controller: server
        ports:
          http:
            port: &port 2283
            primary: true
          api-metrics:
            port: 8081
          microservices-metrics:
            port: 8082
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
    serviceMonitor:
      server:
        service:
          identifier: server
        endpoints:
          - port: api-metrics
            path: /metrics
          - port: microservices-metrics
            path: /metrics
    route:
      server:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Immich
          gethomepage.dev/icon: immich
          gethomepage.dev/description: High performance self-hosted photo and video management solution
          gethomepage.dev/group: Media
          gethomepage.dev/pod-selector: >-
            app.kubernetes.io/instance in (
              immich,
              immich-cnpg,
              immich-dragonfly
            )
        hostnames:
          - immich.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: server
                port: *port
        parentRefs:
          - name: traefik-gateway
            namespace: network
            sectionName: websecure
