---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
    - name: generic-device-plugin
    - name: longhorn
    - name: mosquitto
    - name: node-feature-discovery
    - name: traefik-crds
  path: /kubernetes/apps/home-automation/zigbee2mqtt/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: home-automation
  prune: true
  interval: 15m
  timeout: 5m
  wait: true
