---
name: lint
on: push
jobs:

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: pip install yamllint
      - run: yamllint .

  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: docker://ghcr.io/yannh/kubeconform:v0.7.0
        with:
          entrypoint: /kubeconform
          args: >-
            -output json
            -summary
            -schema-location default
            -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
            -schema-location https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/{{.ResourceKind}}.json
            -ignore-filename-pattern resources/
            -ignore-filename-pattern helmfile\.ya?ml
            -ignore-filename-pattern helm-values\.ya?ml
            -ignore-filename-pattern transformer-config\.ya?ml
            kubernetes/
