---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: lint
on: push

permissions:
  contents: read

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      ansible: ${{ steps.filter.outputs.ansible }}
      kubernetes: ${{ steps.filter.outputs.kubernetes }}
      kubernetes_files: ${{ steps.filter.outputs.kubernetes_files }}
      markdown: ${{ steps.filter.outputs.markdown }}
      markdown_files: ${{ steps.filter.outputs.markdown_files }}
      yaml: ${{ steps.filter.outputs.yaml }}
      yaml_files: ${{ steps.filter.outputs.yaml_files }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          list-files: shell
          filters: |
            ansible:
              - added|modified: 'ansible/**'
            kubernetes:
              - added|modified: 'kubernetes/**'
            markdown:
              - added|modified: '**/*.md'
            yaml:
              - added|modified: '**/*.yaml'
              - added|modified: '**/*.yml'

  ansible-lint:
    needs: changes
    if: ${{ needs.changes.outputs.ansible == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run ansible-lint
        uses: ansible/ansible-lint@7f6abc5ef97d0fb043a0f3d416dfbc74399fbda0 # v26.1.1
        with:
          requirements_file: ansible/requirements.yaml

  kubeconform:
    needs: changes
    if: ${{ needs.changes.outputs.kubernetes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:v0.7.0
        with:
          entrypoint: /kubeconform
          args: >-
            -output json
            -summary
            -schema-location default
            -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
            -schema-location https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/{{.ResourceKind}}.json
            -ignore-filename-pattern resources/
            -ignore-filename-pattern helmfile\.ya?ml
            -ignore-filename-pattern helm-values\.ya?ml
            -ignore-filename-pattern transformer-config\.ya?ml
            ${{ needs.changes.outputs.kubernetes_files }}

  markdownlint:
    needs: changes
    if: ${{ needs.changes.outputs.markdown == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v22
        with:
          globs: '${{ needs.changes.outputs.markdown_files }}'
          separator: ' '

  yamllint:
    needs: changes
    if: ${{ needs.changes.outputs.yaml == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: yamllint ${{ needs.changes.outputs.yaml_files }}
