---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: lint
on: push

permissions:
  contents: read

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      ansible: ${{ steps.filter.outputs.ansible }}
      kubernetes: ${{ steps.filter.outputs.kubernetes }}
      kubernetes_files: ${{ steps.filter.outputs.kubernetes_files }}
      yaml: ${{ steps.filter.outputs.yaml }}
      yaml_files: ${{ steps.filter.outputs.yaml_files }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            ansible:
              - 'ansible/**'
            kubernetes:
              - 'kubernetes/**'
            yaml:
              - '**/*.yaml'
              - '**/*.yml'

  ansible-lint:
    needs: changes
    if: ${{ needs.changes.outputs.ansible == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ansible/ansible-lint@v26.1.1
        with:
          requirements_file: requirements.yaml

  kubeconform:
    needs: changes
    if: ${{ needs.changes.outputs.kubernetes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: docker://ghcr.io/yannh/kubeconform:v0.7.0
        with:
          entrypoint: /kubeconform
          args: >-
            -output json
            -summary
            -schema-location default
            -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
            -schema-location https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/{{.ResourceKind}}.json
            -ignore-filename-pattern resources/
            -ignore-filename-pattern helmfile\.ya?ml
            -ignore-filename-pattern helm-values\.ya?ml
            -ignore-filename-pattern transformer-config\.ya?ml
            ${{ needs.changes.outputs.kubernetes_files }}

  yamllint:
    needs: changes
    if: ${{ needs.changes.outputs.yaml == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: pip install yamllint
      - run: yamllint ${{ needs.changes.outputs.yaml_files }}
