---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Apps
  - ./blocky/ks.yaml
  - ./metallb/ks.yaml
  - ./tailscale-operator/ks.yaml
  - ./traefik/ks.yaml
